### ISSUE TITLE
TA Submission problem

### ISSUE THREAD

**Issue by DimaSeker** [RUBclim/LCZ-Generator-Issues#39]
"Unable to ingest your training area file into the system. Make sure your training areas follow the [template](http://www.wudapt.org/wp-content/uploads/2020/08/WUDAPT_L0_Training_template.kml), and contain polygons with geometries and LCZ labels."

I got the above message when submitting the LCZ Training file
Any idea what might be the problem ?
Is it because i have created my file of TA on Google Earth online  ?

**Comment by theendlessriver13** [comment]
Hey 👋 welcome to GitHub!
Looks like you already fixed your problem? It should not make a difference what tool you use to edit the `.kml` template file, as longs as it keeps the correct file structure (folders for each LCZ with Polyons).
If you still have problems, please send me your training area file, so I can take a look at it.
