### ISSUE TITLE
Creating LCZ TIF Map Greater than 200km x 200km

### ISSUE THREAD

**Issue by azmeeram** [RUBclim/LCZ-Generator-Issues#68]
Hi,

I wanted to ask for any advice you have on creating an LCZ file for multiple cities. The current limitation of the LCZ generator is 200km by 200km. Is there any GIS software with a geoprocessor that allows for a larger spatial extent? Our required domain is large, around 1000km by 1000km,

There is an option to use a clipped global LCZ file, but several urban pixels are missing, so I would prefer the training area method if possible. Please advise.

Thanks,
Amjad

**Comment by jkittner** [comment]
Mhm, not that I am aware of...

What do you mean that several urban pixels are missing? Are they blank or misclassified?

I am not sure what the earthengine limit is for processing before it times out. We had issues in the past with that...

I can offer you to send me your TAs so I can try it locally (disabling the 2.5° limit). Send it to the lcz generator email. Multiple iteration may be hard though - but let's see first if it's even possible.

**Comment by azmeeram** [comment]
Hi Jonas,

Thanks for your reply. I mean that in the[ global LCZ map](https://lcz-generator.rub.de/global-lcz-map), at least for cities like Riyadh, there are many misclassified pixels.

It would be a great help. I am looking at an area of 6° which will encompass major cities in Saudi Arabia like Jeddah, Makkah, and Madinah; if it is okay with you, I will send you the TAs for all these cities by the end of this week to [lcz-generator@rub.de](mailto:lcz-generator@rub.de). You can try to let me know if it is possible.

Appreciate your help,
Thanks,
Amjad

**Comment by jkittner** [comment]
Earthengine unfortunately cannot handle such large domains. It runs out of memory.
