### ISSUE TITLE
Google earth pro error when creating training areas

### ISSUE THREAD

**Issue by joaovmartinelli-24** [RUBclim/LCZ-Generator-Issues#70]
**I know this probably isn't the right place, but I can't seem to solve this problem.** 

I created several training areas, reaching LCZ 10 without any problems.
Then, when continuing the process for the last seven zones, an error occurred in Google Earth Pro, displaying the following message: “An unexpected error has occurred and the program needs to be closed”. When reopening Google Earth Pro, the last training areas are not saved. 
If anyone can help me with this, I'd really appreciate it.

**Comment by jkittner** [comment]
Hi, I am not sure what's happening there, but that sounds more like an internal issue with google earth than with the LCZ-Generator.
I can only give you the usual hints like:
- make sure you follow these guidelines: https://www.wudapt.org/digitize-training-areas/
- try updating to the latest version of google earth
- create a new TA file and test if you are able to create polygons in all folders
- try editing a TA file from someone else (you can download that from the LCZ-Generator) see what they did differently and if the issue you're describing also comes up when adding TAs to their file
- Try editing your file on a different computer to see if it's specific to your machine

If you can't figure this out, maybe upload your KML-File to this issue, so someone can have a look at the file.

**Comment by joaovmartinelli-24** [comment]
Thanks @jkittner!
In fact, the problem I'm reporting seems to be related to GE, not LCZ Generator. However, as I haven't managed to solve it yet, I thought perhaps someone could help me understand what is causing the error. 
I tried attaching the KML file, but this file type is not supported.

**Comment by jkittner** [comment]
this seems to be resolved since there is no further activity.
